# --- docker-compose.yml ---
services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u${MARIADB_USER} -p${MARIADB_PASSWORD} -e 'SELECT 1' ${MARIADB_DATABASE}"]
      interval: 15s
      timeout: 5s
      retries: 10
    networks:
      appnet:
        aliases: [db]

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DSN: ${DB_DSN}
      TZ: ${TZ}
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_LOG_LEVEL: ${BACKEND_LOG_LEVEL}
    expose: ["8000"]
    networks:
      appnet:
        aliases: [backend]

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DSN: ${DB_DSN}
      TZ: ${TZ}
      FROM_STATION: ${FROM_STATION}
      TO_STATION: ${TO_STATION}
      IRAIL_LANG: ${IRAIL_LANG}
      POLL_SECONDS: ${POLL_SECONDS}
      USER_AGENT: ${USER_AGENT}
    networks:
      appnet:
        aliases: [worker]

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      BACKEND_URL: ${BACKEND_URL:-http://backend:8000}
      TZ: ${TZ}
      PORT: 3000
    depends_on:
      - backend
    expose: ["3000"]
    networks:
      appnet:
        aliases: [frontend]

volumes:
  dbdata:

networks:
  appnet:
    driver: bridge
