version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: sncb-db
    environment:
      - MARIADB_DATABASE=sncbslac
      - MARIADB_USER=app
      - MARIADB_PASSWORD=change_me
      - MARIADB_ROOT_PASSWORD=change_me_root
      - TZ=Europe/Brussels
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u$$MARIADB_USER -p$$MARIADB_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - internal

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: sncb-backend:local
    container_name: sncb-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=Europe/Brussels
      - DB_DSN=mysql+pymysql://app:change_me@db:3306/sncbslac
      - LOG_LEVEL=INFO
      - DEBUG=false
    ports:
      - "8000:8000"
    networks:
      - internal
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: sncb-frontend:local
    container_name: sncb-frontend
    environment:
      - TZ=Europe/Brussels
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - NEXT_PUBLIC_API_BASE_URL=/api
    ports:
      - "13000:3000"   # <— changement ici (évite le conflit avec 3000)
    networks:
      - internal
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    image: sncb-worker:local
    container_name: sncb-worker
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=Europe/Brussels
      - DB_DSN=mysql+pymysql://app:change_me@db:3306/sncbslac
      - FROM_STATION=Tournai
      - TO_STATION=Bruxelles-Central
      - IRAIL_LANG=fr
      - POLL_SECONDS=120
      - USER_AGENT=SNCB-Slac/1.0 (+https://sncb.terminalcommun.be)
      - DEBUG=false
      - LOG_LEVEL=INFO
    networks:
      - internal
    restart: unless-stopped

volumes:
  dbdata:

networks:
  internal:
