services:
  db:
    image: mariadb:11
    container_name: sncb-db
    environment:
      MARIADB_DATABASE: sncbslac
      MARIADB_USER: app
      MARIADB_PASSWORD: change_me
      MARIADB_ROOT_PASSWORD: root_pwd_change_me
      TZ: Europe/Brussels
    volumes:
      - dbdata:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mariadb", "-h127.0.0.1", "-uapp", "-pchange_me", "sncbslac", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - internal

  backend:
    container_name: sncb-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DB_DSN: mysql+pymysql://app:change_me@db:3306/sncbslac
      TZ: Europe/Brussels
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "18000:8000"   # debug local ; retire si Traefik uniquement
    networks:
      - internal

  worker:
    container_name: sncb-worker
    build:
      context: .
    dockerfile: worker/Dockerfile
    environment:
      FROM_STATION: Tournai
      TO_STATION: Bruxelles-Central
      IRAIL_LANG: fr
      POLL_SECONDS: "120"
      USER_AGENT: SNCB-Slac/1.0 (+https://sncb.terminalcommun.be)
      DB_DSN: mysql+pymysql://app:change_me@db:3306/sncbslac
      TZ: Europe/Brussels
      DEBUG: "false"
      LOG_LEVEL: INFO
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  frontend:
    container_name: sncb-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: "3000"
      NEXT_PUBLIC_API_BASE_URL: /api
      TZ: Europe/Brussels
    depends_on:
      backend:
        condition: service_started
    ports:
      - "13000:3000"   # debug local ; si Traefik, tu peux retirer
    networks:
      - internal
      # - proxy        # décommente + configure labels si Traefik

volumes:
  dbdata:

networks:
  internal:
    driver: bridge
  # proxy:
  #   external: true
  #   name: dokploy-network
