services:
  db:
    image: mariadb:11
    container_name: sncb-db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: sncbslac
      MARIADB_USER: app
      MARIADB_PASSWORD: change_me
      TZ: Europe/Brussels
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h127.0.0.1 -u$MARIADB_USER -p$MARIADB_PASSWORD -e 'SELECT 1' $MARIADB_DATABASE"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


  backend:
    build:
      context: ./backend
    container_name: sncb-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=Europe/Brussels
      - MARIADB_HOST=db
      - MARIADB_PORT=3306
      - MARIADB_DATABASE=sncbslac
      - MARIADB_USER=app
      - MARIADB_PASSWORD=change_me
    ports:
      - "18000:8000"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  worker:
    build:
      context: ./worker
    container_name: sncb-worker
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=Europe/Brussels
      - MARIADB_HOST=db
      - MARIADB_PORT=3306
      - MARIADB_DATABASE=sncbslac
      - MARIADB_USER=app
      - MARIADB_PASSWORD=change_me
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
    container_name: sncb-frontend
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - NEXT_PUBLIC_API_BASE_URL=https://sncb.terminalcommun.be/api
      - TZ=Europe/Brussels
    ports:
      - "13000:3000"
    networks:
      - internal
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.routers.sncb-frontend.rule=Host(`sncb.terminalcommun.be`)"
      - "traefik.http.routers.sncb-frontend.entrypoints=websecure"
      - "traefik.http.routers.sncb-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.sncb-frontend.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:3000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  dbdata:

networks:
  internal:
    driver: bridge
  proxy:
    external: true
    name: dokploy-network
