version: "3.9"

services:
  db:
    image: mariadb:11.4
    container_name: ${COMPOSE_PROJECT_NAME:-sncb}-db-1
    environment:
      MARIADB_DATABASE: sncbslac
      MARIADB_USER: app
      MARIADB_PASSWORD: change_me
      MARIADB_ROOT_PASSWORD: change_me_root
      TZ: Europe/Brussels
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -u$${MARIADB_USER} -p$${MARIADB_PASSWORD} --silent"]
      interval: 20s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-sncb}-backend-1
    environment:
      DB_DSN: mysql+pymysql://app:change_me@db:3306/sncbslac
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: 8000
      BACKEND_LOG_LEVEL: info
      TZ: Europe/Brussels
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8000/healthz"]
      interval: 20s
      timeout: 3s
      retries: 5

  worker:
    build:
      context: .                # <-- IMPORTANT: contexte = racine du repo
      dockerfile: worker/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-sncb}-worker-1
    environment:
      DB_DSN: mysql+pymysql://app:change_me@db:3306/sncbslac
      FROM_STATION: Tournai
      TO_STATION: Bruxelles-Central
      IRAIL_LANG: fr
      POLL_SECONDS: 120
      USER_AGENT: SNCB-Slac/1.0 (+https://sncb.terminalcommun.be)
      TZ: Europe/Brussels
      DEBUG: "false"
      LOG_LEVEL: "INFO"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    container_name: ${COMPOSE_PROJECT_NAME:-sncb}-frontend-1
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      NEXT_PUBLIC_API_BASE_URL: https://sncb.terminalcommun.be/api
      TZ: Europe/Brussels
    depends_on:
      backend:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:3000/health"]
      interval: 20s
      timeout: 3s
      retries: 5

volumes:
  dbdata:
