services:
  db:
    image: mariadb:11
    container_name: sncb-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: sncbslac
      MARIADB_USER: app
      MARIADB_PASSWORD: change_me
      MARIADB_ROOT_PASSWORD: change_root
      TZ: Europe/Brussels
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      # ✅ Ping sans mot de passe, purement connectivité/availability
      test: ["CMD-SHELL", "mariadb-admin ping -h127.0.0.1 --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    networks:
      - internal

  backend:
    container_name: sncb-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DSN: mysql+pymysql://app:change_me@db:3306/sncbslac
      HOST: 0.0.0.0
      PORT: 8000
      TZ: Europe/Brussels
      LOG_LEVEL: INFO
    ports:
      - "18000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s
    networks:
      - internal

  frontend:
    container_name: sncb-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      NEXT_PUBLIC_API_BASE_URL: /api
      TZ: Europe/Brussels
    ports:
      - "13080:3000"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://127.0.0.1:3000/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\""]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s
    networks:
      - internal

  worker:
    container_name: sncb-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DSN: mysql+pymysql://app:change_me@db:3306/sncbslac
      FROM_STATION: Tournai
      TO_STATION: Bruxelles-Central
      IRAIL_LANG: fr
      POLL_SECONDS: "120"
      USER_AGENT: SNCB-Slac/1.0 (+https://sncb.terminalcommun.be)
      TZ: Europe/Brussels
      DEBUG: "false"
      LOG_LEVEL: INFO
    networks:
      - internal

networks:
  internal:

volumes:
  dbdata:
