backend:
  build:
    context: .           # <— racine du repo
    dockerfile: backend/Dockerfile
  container_name: sncb-backend
  depends_on:
    db:
      condition: service_healthy
  environment:
    - TZ=Europe/Brussels
    - MARIADB_HOST=db
    - MARIADB_PORT=3306
    - MARIADB_DATABASE=sncbslac
    - MARIADB_USER=app
    - MARIADB_PASSWORD=change_me
  ports:
    - "18000:8000"
  networks:
    - internal
  healthcheck:
    test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/healthz || exit 1"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s

worker:
  build:
    context: .           # <— racine du repo
    dockerfile: worker/Dockerfile
  container_name: sncb-worker
  depends_on:
    db:
      condition: service_healthy
  environment:
    - TZ=Europe/Brussels
    - MARIADB_HOST=db
    - MARIADB_PORT=3306
    - MARIADB_DATABASE=sncbslac
    - MARIADB_USER=app
    - MARIADB_PASSWORD=change_me
  networks:
    - internal
